-- Generated by nwg-displays on 2026-10-01 at 16:54:34. Do not edit manually.

hl.monitor({
    output = "desc:AU Optronics 0xD49C",
    mode = "1920x1200@60.01",
    position = "640x640",
    scale = 1.5,
    vrr = 0
})
hl.monitor({
    output = "desc:Dell Inc. DELL S2722DC 6NSGHD3",
    mode = "2560x1440@74.97",
    position = "1920x288",
    scale = 1.25,
    vrr = 0
})
hl.monitor({
    output = "desc:Dell Inc. DELL S2721DS 5LWPQ43",
    mode = "2560x1440@74.97",
    position = "3968x288",
    scale = 1.25,
    vrr = 0
})
