[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "shell 'code .' --orphan"
desc = "Open current folder in VS Code"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter folder or open file"