cursor #161d1c
cursor_text_color #3f4947

foreground            #161d1c
background            #f4fbf9
selection_foreground  #ffffff
selection_background  #b0ccc8
url_color             #006a64

# black
color8   #161d1c
color0   #4c4c4c

# red
color1   #ba1a1a
color9   #c49ea0

# green
color2   #161d1c
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
/* color4  #8f8aac */
color4  #006a64
color12 #a39ec4

# magenta
color5   #ba1a1a
color13  #c49ec4

# cyan
color6   #161d1c
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0